const Constants = {
  BACKGROUND_COLOR: '#FAFAFA',
  DEEP_COLOR: '#2D2D34',
  SHALLOW_COLOR: '#9C9D9C',
  MIDDLE_COLOR: '#4A4A4A',
  SHADOW_COLOR: '#7A7A7A',
  COMMENT_TEXT_BACKGROUND_COLOR: '#F9F9F9',
  COMMENT_ICON_COLOR: '#c7c7c7',
  COLLECTION_MARGIN: 15,
  IMAGE_SIZE_RATIOS: [9 / 16, 3 / 4, 4 / 3],
};
export default Constants;
